SELECT * FROM empleados;
SELECT * FROM departamentos;
SELECT nombre_depto FROM departamentos;
SELECT nombre, sal_emp FROM empleados;
SELECT comision_emp FROM empleados;
SELECT * FROM empleados WHERE cargo_emp="Secretaria";
SELECT * FROM empleados WHERE cargo_emp="Vendedor" ORDER BY nombre ASC;
SELECT nombre, cargo_emp FROM empleados ORDER BY sal_emp ASC;
SELECT nombre_jefe_depto FROM departamentos WHERE ciudad= "Ciudad Real";
SELECT nombre AS Nombre, cargo_emp AS Cargo FROM empleados;
SELECT sal_emp, comision_emp FROM empleados WHERE id_depto=2000 ORDER BY comision_emp ASC;
SELECT Nombre, SUM(sal_emp + comision_emp + 500) AS 'Total a Pagar' FROM empleados WHERE id_depto=3000 GROUP BY Nombre ORDER BY Nombre ASC;
SELECT nombre FROM empleados WHERE nombre LIKE 'j%';
SELECT sal_emp, comision_emp, (sal_emp + comision_emp) AS 'Salario total' FROM empleados WHERE comision_emp>10000;
SELECT sal_emp, comision_emp, (sal_emp + comision_emp) AS 'Salario total' FROM empleados WHERE comision_emp<10000;
SELECT nombre,sal_emp, comision_emp FROM empleados WHERE comision_emp>sal_emp;
SELECT nombre FROM empleados WHERE comision_emp<= 0.3 * sal_emp;
SELECT nombre FROM empleados WHERE nombre NOT LIKE '%MA%';
SELECT id_depto, nombre_depto FROM departamentos WHERE nombre_depto IN ('Ventas', 'Investigación', 'Mantenimiento');
SELECT id_depto, nombre_depto FROM departamentos WHERE nombre_depto NOT IN ('Ventas', 'Investigación', 'Mantenimiento');
SELECT MAX(sal_emp) FROM empleados;
SELECT nombre FROM empleados ORDER BY nombre DESC LIMIT 1;
SELECT MAX(sal_emp) AS 'Salario Máx', MIN(sal_emp) AS 'Salario Min', MAX(sal_emp)-MIN(sal_emp) AS 'Diferencia' FROM empleados;
SELECT id_depto, AVG(sal_emp) AS 'Salario promedio' FROM empleados GROUP BY id_depto;
SELECT id_depto, COUNT(nombre) AS 'Cantidad empleados' FROM empleados GROUP BY id_depto HAVING COUNT(nombre)>3;
SELECT id_depto, COUNT(nombre) AS 'Cantidad empleados' FROM empleados GROUP BY id_depto HAVING COUNT(nombre)=0;
SELECT id_depto, nombre, sal_emp FROM empleados WHERE sal_emp>=(SELECT AVG(sal_emp) FROM empleados) ORDER BY id_depto;